# Configuration Gitpod pour une application Flutter

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Préparation Flutter
    command: |
      flutter pub get

  - name: Lancer application
    command: |
      # Remplacez 'main.dart' par le chemin approprié si nécessaire
      flutter run

vscode:
  extensions:
    - Dart-Code.flutter

ports:
  - port: 8080
    onOpen: open-preview

# (optionnel) Commandes à exécuter au démarrage
init:
  - flutter doctor
