FROM gitpod/workspace-flutter
RUN sudo apt-get update && \ 
    sudo apt-get install -y curl unzip xz-utils && \
    sudo apt-get- clean

RUN flutter config --enable-web && \
    flutter upgrade --force
